name: "DuckChatIrc"
version: "${version}-${project.build.number}"
main: "org.cyberiantiger.minecraft.duckchat.irc.Main"
website: "http://dev.bukkit.org/server-mods/duckchat-irc/"
depend:
  - DuckChat
commands: 
  duckchatirc:
    description: The main DuckChatIrc command.
    usage: '/<command> reload'
    aliases: dcirc
    permission: duckchatirc
permissions: 
    duckchatirc.reload:
      default: op
      description: Allow usage of the reload command.
